FROM node:20-bullseye

RUN apt update && \
	apt install -y vim procps postgresql-client && \
	apt clean

WORKDIR /app

# パッケージインストール
RUN npm install express typeorm pg concurrently reflect-metadata bcrypt dotenv jsonwebtoken ms cookie-parser cors
RUN npm install --save-dev typescript ts-node-dev @types/express @types/cors

# TypeORMプロジェクトを初期化
RUN npx typeorm init --database postgres

# srcファイルをコピー
COPY ./src .

# TypeScriptをビルドする
RUN npm run build

# ポート番号を指定する
EXPOSE 8000

# migrationを生成する前に、PostgreSQLサーバーを起動するスクリプトを実行する
CMD ["sh", "-c", "service postgresql start && npm run migration:generate src/migration/init && npm start"]
