version: '3.8'
services:
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgresql
    tty: true
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
    env_file: ./.env
    environment:
      - TZ:Asia/Tokyo
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DB}
volumes:
  postgresql:
    driver: local
